### ISSUE TITLE
New chip support / PR maintenance and documentation

### ISSUE THREAD

**Issue by LorenzMeier** [blacksphere/blackmagic#102]
Hi,

We would like to adopt the black magic probe as default for Dronecode and we would like to avoid having to maintain our own codebase and docs. We would love to help to make this great project more visible and the default goto solution for JTAG / SWD. There are a few pain points however:

- Documentation: Updating the BMP Firmware is a regular requirement as new MCUs are coming out which are not yet supported. The hacking page is not user friendly enough yet: https://github.com/blacksphere/blackmagic/wiki/Hacking. Can we can get access to wiki edits to help creating a user-facing firmware upgrade page? Otherwise we would have to do that in our own documentation.

- Chip support pull requests: Is there a chance to get those reviewed and merged faster? They tend to sit for several months.

@pavel-kirienko @bendyer @tridge FYI.

**Comment by gsmcmullin** [comment]
Hi Lorenz

Thank you for making contact and raising the issue.

Regarding documentation, any signed in Github user should be able to edit the wiki pages.  You don't require push access to the code in order to do this.  Please confirm if this works for you.  If not, I'll bring it up with Github support.

There are a few reasons for my tardiness merging PRs.   An obvious one is just finding time to review them.  People adding support for new devices tend to copy existing drivers and make tiny edits, instead of factoring out the common parts. This proves to be a significant maintenance headache.  Most often I don't even have the devices in question, so I don't want to do the refactoring and break anything.  I also have a non-public branch where I've been working on a rewrite in C++.  I haven't made this public because I'm not entirely happy with it yet.  Merging support into that branch is an additional overhead.

Please join the Gitter channel to discuss how we can work together to improve things. https://gitter.im/blacksphere/blackmagic

Gareth
