### ISSUE TITLE
Redirect UART output to GDB console

### ISSUE THREAD

**Issue by joric** [blacksphere/blackmagic#379]
Since Blackmagic has a built-in second COM port is it possible to redirect its output to the GDB console so I wouldn't need to launch two terminals? Maybe it's already supported? Project I'm debugging https://github.com/joric/mitosis/tree/devel/mitosis-bluetooth

**Comment by UweBonnes** [comment]
Why do you want to do that?

**Comment by joric** [comment]
Because launching a second terminal seems pretty unnecessary, there is no tracing hardware in the nRF51 series anyway.

**Comment by gsmcmullin** [comment]
This is not currently supported, nor is it a planned feature.

It could be implemented with some limitations. Most importantly, characters can be received on the UART at any time, but output can only be sent to GDB when the target is attached and running.  It would also require adding a new mechanism to configure the baud rate and frame format for the UART.

The USB-UART feature is prefered because it works completely independently from the GDB connection.

**Comment by gsmcmullin** [comment]
We have no intention to support redirection of the UART to the GDB console, so I'm closing this issue.
The discussion has gone off topic.  Please reopen #320 if that is still a problem and discuss there.
