### ISSUE TITLE
BMP serial interface ignores write (PC->device) bigger 16 byte. 

### ISSUE THREAD

**Issue by UweBonnes** [blacksphere/blackmagic#538]
When writing blocks of > 16 bytes without delay between character, BMP ignores the whole block.

**Comment by zyp** [comment]
I just ran into this issue myself. Issue is present both in 2b4000b which I had loaded on my BMP and 08bb4d5 which is current master.

Looking at captures for the USB traffic, the device returns a STALL handshake to large packets: 
[1](https://bin.jvnv.net/file/GtKiI.png) [2](https://bin.jvnv.net/file/8GyeA.png)

First capture is from actual use, where I first spotted the problem. Second capture is reproducing the problem by simply doing `cat /dev/zero > /dev/…`.

There's not really any reasonable reason for why the device should return a STALL in this situation and I don't see anything suspicious in `usbuart.c` either, so I suspect this might be something that will have to be fixed in libopencm3.

**Comment by zyp** [comment]
Found the problem. 3e3e450 reduced the size of the buffer for the endpoint without also reducing the max packet size in the endpoint descriptor, so hardware only expects 32B packets while telling the host it can send 64B packets, and when receiving a larger packet than expected, the STALL handshake signals that error.
